---
- name: 
  hosts: master,node
  become: yes
  vars:
    timesync_net_services:
      - hostname: pool.ntp.org
        iburst: true
      - hostname: ntp.aliyun.com
        iburst: true
    #软件版本，注意containerd的不带v
    runc: v1.2.0-rc.3
    containerd: 1.7.14
    crictl: v1.31.1
    # 设置构架
    architecture: amd64

  roles:
    - role: commit_swap
    - linux-system-roles.timesync

  tasks: 
    - name: update hostname
      hostname:
        name: "{{ hostname | default('localhost.localdomain') }}"
        use: systemd  

    - name: update hosts 
      template:
        src: hosts.j2
        dest: /etc/hosts
        backup: yes

    - name: Ensure .ssh directory exists
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: Generate SSh key pair
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_rsa
        type: rsa
        size: 4096
        state: present
      register: ssh_key
      when: '"master" in group_names'

    - name: add ssh keyecdsa public
      template:
        src: known_hosts.j2
        dest: /root/.ssh/known_hosts
        mode: "0600"
        backup: yes
      when: "'master' in group_names"

    - name: 获取公钥
      shell: cat /root/.ssh/id_rsa.pub
      register: master_pubkey
      when: "'master' in group_names"

    - name: 将公钥保存到变量
      set_fact:
          master_pubkey_content: "{{ master_pubkey.stdout }}"
      when: "'master' in group_names"

    - name: 在node组生成authorized_keys文件
      template: 
        src: pubkey.j2
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: "0600"
        backup: yes
      when: "'node' in group_names"

    - name: ssh configb pubkeyAuthenication yes
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: "^#?PubkeyAuthentication\\s+.*"
        line: "PubkeyAuthentication yes"

    - name: ssh config PermitRootLogin yes
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin\\s+.*"
        line: "PermitRootLogin yes"

    - name: restart sshd
      systemd_service: 
        state: restarted
        daemon_reload: true
        name: sshd

    - name: 关闭防火墙
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_facts.services['firewalld.service'] is defined

    - name: 关闭防火墙
      systemd:
        name: iptables
        state: stopped
        enabled: no
      when: ansible_facts.services['iptables.service'] is defined
      ignore_errors: yes

    - name: 关闭selinux
      selinux: 
        policy: targeted
        state: permissive

    - name: 安装软件包
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
          - epel-release
          - podman
          - bash-completion
          - ipset
          - ipvsadm

    - name: 添加内核参数
      lineinfile:
        path: /etc/modules-load.d/containerd.conf
        line: "{{ item }}"
        create: yes
      with_items:
          - 'overlay'
          - 'br_netfilter'

    - name: 添加ipvs配置文件
      lineinfile:
        path: /etc/modules-load.d/ipvs.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - 'ip_vs'
        - 'ip_vs_rr'
        - 'ip_vs_wrr'
        - 'ip_vs_sh'

    - name: 加载内核
      shell: modprobe "{{ item }}"
      with_items:
        - 'overlay'
        - 'br_netfilter'
        - 'ip_vs'
        - 'ip_vs_rr'
        - 'ip_vs_wrr'
        - 'ip_vs_sh'

    - name: 添加转发配置文件
      lineinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - 'net.bridge.bridge-nf-call-ip6tables = 1'
        - 'net.bridge.bridge-nf-call-iptables = 1'
        - 'net.ipv4.ip_forward = 1'
        - 'user.max_user_namespaces=28633'

    - name: 重载配置
      shell: sysctl -p /etc/sysctl.d/99-kubernetes-cri.conf

    - name: download packages
      get_url:
        url: "{{ item }}"
        dest: /tmp 
      with_items: #默认是x86构架，如是其他构架，按需修改
        - 'https://github.com/containerd/containerd/releases/download/v{{ containerd }}/containerd-{{ containerd }}-linux-{{ architecture }}.tar.gz'
        - 'https://github.com/opencontainers/runc/releases/download/{{ runc }}/runc.{{ architecture }}'
        - 'https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl }}/crictl-{{ crictl }}-linux-{{ architecture }}.tar.gz'

    - name: 解压和安装软件
      unarchive:
        src: /tmp/containerd-{{ containerd }}-linux-{{ architecture }}.tar.gz
        dest: /usr/local
        remote_src: yes

    - name: 解压crictl
      unarchive:
        src: /tmp/crictl-{{ crictl }}-linux-{{ architecture }}.tar.gz
        dest: /tmp
        remote_src: yes

    - name: 安装crictl
      shell: install -m 755 /tmp/crictl /usr/local/bin/crictl

    - name: 安装runc
      shell: install -m 755 /tmp/runc.{{ architecture }} /usr/local/sbin/runc
      
    - name: 生成并配置containerd配置文件
      shell: "{{ item }}"
      with_items: 
        - mkdir -p /etc/containerd
        - /usr/local/bin/containerd config default > /etc/containerd/config.toml
        - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
        - sed -i 's,sandbox_image = "registry.k8s.io/pause:3.8",sandbox_image = "registry.aliyuncs.com/google_containers/pause:3.9",g' /etc/containerd/config.toml

    - name: 下载systemd tages
      get_url:
        url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        dest: /etc/systemd/system

    - name: 元神启动
      shell: "{{ item }}"
      with_items:
        - systemctl daemon-reload
        - systemctl enable containerd --now 
        - systemctl status containerd

    # 安装版本在repo中指定，指定那版本后续安装就是那个版本。
    - name: copy k8s repo to /etc/yum.repos.d/
      copy:
        src: k8s.repo
        dest: /etc/yum.repos.d/k8s.repo
      
    - name: install kubelet、kubeadm 、kubectl
      yum:
        name: "{{ item }}"
        disable_excludes: kubernetes
        state: latest
      with_items:
        - kubelet
        - kubeadm
        - kubectl']
      tags: install_package

    - name: 下kube-flannel文件
      get_url:
        url: https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
        dest: /root/
      when: "'master' in group_names"

    - name: 添加kubectl、kubeadm自动补全
      shell: "{{ item }}"
      with_items:
        - echo "source <(kubectl completion bash)" >> /root/.bashrc
        - echo "source <(kubeadm completion bash)" >> /root/.bashrc

    - name: enable kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes
      notify: reboot system

  handlers:
    - name: reboot system
      reboot:

